"use client";
import {useEffect,useRef,useState} from "react";import Brand from "@/components/Brand";import {createSupabaseBrowser} from "@/lib/supabase";import {Song,Event} from "@/lib/types";
const sb=createSupabaseBrowser();
export default function Guest({params}:{params:Promise<{slug:string}>}){
 const[slug,setSlug]=useState(""),[event,setEvent]=useState<Event|null>(null),[q,setQ]=useState(""),[songs,setSongs]=useState<Song[]>([]),[yt,setYt]=useState<Song[]>([]),[pick,setPick]=useState<Song|null>(null),[name,setName]=useState(""),[confirmation,setConfirmation]=useState<any>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[searching,setSearching]=useState(false);const requestRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{params.then(async({slug})=>{setSlug(slug);if(sb){const {data}=await sb.rpc("get_public_event",{p_slug:slug});if(data){setEvent({id:data.id,slug:data.slug,name:data.name,venue:data.venue,date:data.eventDate,requestsOpen:data.requestsOpen,openYouTube:data.openYouTube,rating:data.rating,averageSongMinutes:Number(data.averageSongMinutes||4.5),newSingerPolicy:data.newSingerPolicy});await loadCurated(slug,"");}setLoading(false)}})},[params]);
 useEffect(()=>{if(pick)requestAnimationFrame(()=>requestRef.current?.scrollIntoView({behavior:"smooth",block:"center"}))},[pick]);
 async function loadCurated(s:string,query:string){if(!sb)return;const {data}=await sb.rpc("search_curated_songs",{p_slug:s,p_query:query.trim()});if(data)setSongs(data.map((x:any)=>({id:x.id,title:x.title,artist:x.artist,videoId:x.video_id||"",channel:x.channel||"Four Dogs",thumbnail:x.thumbnail||"",genre:x.genre||"Karaoke",rating:x.content_rating||"GENERAL",tags:[],source:"CURATED",verified:true})));}
 async function search(){setError("");setPick(null);setSearching(true);await loadCurated(slug,q);setYt([]);if(event?.openYouTube&&q.trim().length>=2){try{const r=await fetch(`/api/youtube/search?q=${encodeURIComponent(q)}`),d=await r.json();if(!r.ok)throw new Error(d.error||"YouTube search failed");setYt((d.results||[]).map((x:any)=>({id:`yt:${x.videoId}`,title:x.title,artist:x.channel,videoId:x.videoId,channel:x.channel,thumbnail:x.thumbnail||"",genre:"Karaoke",rating:"GENERAL",tags:[],source:"YOUTUBE",verified:false})));}catch(e:any){setError(e.message)}}setSearching(false)}
 async function submit(){if(!pick||!name.trim()||!event||!sb)return;setError("");let data:any,error:any;if(pick.source==="YOUTUBE")({data,error}=await sb.rpc("submit_youtube_request",{p_slug:slug,p_singer:name,p_video_id:pick.videoId,p_title:pick.title,p_channel:pick.channel,p_thumbnail:pick.thumbnail||null}));else({data,error}=await sb.rpc("submit_guest_request",{p_slug:slug,p_singer:name,p_song_id:pick.id}));if(error){setError(error.message);return}setConfirmation({name:name.trim(),title:pick.title,position:Number(data.position),wait:Number(data.waitMinutes),source:pick.source});setPick(null);setName("");window.scrollTo({top:0,behavior:"smooth"})}
 function selectSong(s:Song){setPick(s);setConfirmation(null)}
 if(loading)return <main className="shell"><Brand/><div className="card">Loading event…</div></main>;if(!event)return <main className="shell"><Brand/><div className="card">Event not found.</div></main>;const results=[...songs,...yt];
 return <main className="shell"><Brand/><div className="card"><h1>{event.name}</h1><p>{event.venue}</p></div>{error&&<div className="card"><b>{error}</b></div>}{confirmation&&<div className="card"><h2>YOUR REQUEST IS IN!</h2><p><b>{confirmation.name}</b><br/>{confirmation.title}</p><p>Approximate position: <b>#{confirmation.position}</b><br/>Estimated wait: <b>{confirmation.wait} minutes</b></p></div>}<div className="card"><label>Search songs or artists</label><input className="input" value={q} onChange={x=>setQ(x.target.value)} onKeyDown={x=>x.key==="Enter"&&search()} placeholder="Tennessee Whiskey"/><button className="btn" disabled={searching} onClick={search}>{searching?"SEARCHING…":"SEARCH"}</button><p className="muted">Search includes public YouTube karaoke results. YouTube results require host approval.</p></div>{pick&&<div className="card" ref={requestRef}><span className="status">SELECTED SONG</span><h2>{pick.title}</h2><p>{pick.artist}</p><label>Your singer name</label><input autoFocus className="input" value={name} onChange={x=>setName(x.target.value)} onKeyDown={x=>x.key==="Enter"&&name.trim()&&submit()} maxLength={40} placeholder="Enter your name"/><div className="row"><button className="btn" disabled={!name.trim()} onClick={submit}>SUBMIT REQUEST</button><button className="btn secondary" onClick={()=>setPick(null)}>Choose Another</button></div></div>}{results.map(s=><div className="card song" key={s.id}>{s.thumbnail&&<img src={s.thumbnail} alt=""/>}<div><b>{s.title}</b><div>{s.artist}</div><span className="pill">{s.source==="YOUTUBE"?"UNVERIFIED YOUTUBE RESULT":"CURATED"}</span></div><span className="spacer"/><button className="btn" onClick={()=>selectSong(s)}>{pick?.id===s.id?"SELECTED":"SELECT SONG"}</button></div>)}</main>
}